### ISSUE TITLE
Installations problem (node v.0.12.2 and arm)

### ISSUE THREAD

**Issue by denbruev** [fuwaneko/node-protobuf#61]
Is it possible to build node-protobuf for arm architecture?
I tried to build it with cross compiler and got this error:

npm install --target_arch=arm node-protobuf
|
> node-protobuf@1.2.12 install /home/user/Downloads/node-v0.12.2-linux-x86/node_modules/node-protobuf
> node-gyp rebuild

make: Entering directory `/home/user/Downloads/node-v0.12.2-linux-x86/node_modules/node-protobuf/build'
  CXX(target) Release/obj.target/protobuf/src/init.o
cc1plus: warning: include location "/usr/local/include" is unsafe for cross-compilation [-Wpoison-system-directories]
In file included from /home/user/.node-gyp/0.10.27/deps/v8/include/v8.h:41:0,
                 from ../src/common.h:4,
                 from ../src/init.cpp:1:
/home/user/.node-gyp/0.10.27/deps/v8/include/v8stdint.h:34:19: fatal error: stdio.h: No such file or directory
 #include <stdio.h>
                   ^
compilation terminated.
make: *** [Release/obj.target/protobuf/src/init.o] Error 1
make: Leaving directory `/home/user/Downloads/node-v0.12.2-linux-x86/node_modules/node-protobuf/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/user/Downloads/node-v0.12.2-linux-x86/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:807:12)
gyp ERR! System Linux 3.11-2-686-pae
gyp ERR! command "node" "/home/user/Downloads/node-v0.12.2-linux-x86/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/user/Downloads/node-v0.12.2-linux-x86/node_modules/node-protobuf
gyp ERR! node -v v0.10.27
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Linux 3.11-2-686-pae
npm ERR! argv "/home/user/Downloads/node-v0.12.2-linux-x86/bin/node" "/home/user/Downloads/node-v0.12.2-linux-x86/bin/npm" "install" "--target_arch=arm" "node-protobuf"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! node-protobuf@1.2.12 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-protobuf@1.2.12 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-protobuf package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-protobuf
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/Downloads/node-v0.12.2-linux-x86/bin/npm-debug.log
[npm-debug.log.zip](https://github.com/fuwaneko/node-protobuf/files/130894/npm-debug.log.zip)

**Comment by fuwaneko** [comment]
You need to check your compiler infrastructure. Error message is pretty clear: you don't have stdio.h header. [Suggestions from SO](http://stackoverflow.com/questions/23011367/arm-linux-gnu-gcc-fatal-error-stdio-h-no-such-file-or-directory).

**Comment by fuwaneko** [comment]
Closing due to inactivity.
